export const ADD_MERCHANT = 'ADD_MERCHANT';
export const ADD_MERCHANT_SUCCESS = 'ADD_MERCHANT_SUCCESS';
export const ADD_MERCHANT_FAILURE = 'ADD_MERCHANT_FAILURE';

export const GET_MERCHANTS = 'GET_MERCHANTS';
export const GET_MERCHANTS_SUCCESS = 'GET_MERCHANTS_SUCCESS';
export const GET_MERCHANTS_FAILURE = 'GET_MERCHANTS_FAILURE';

export const GET_MERCHANT = 'GET_MERCHANT';
export const GET_MERCHANT_SUCCESS = 'GET_MERCHANT_SUCCESS';
export const GET_MERCHANT_FAILURE = 'GET_MERCHANT_FAILURE';
